name: Send Menu

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * THU"
  

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run
      env:
        ZULIP_API_KEY: ${{ secrets.ZULIP_API_KEY }} 
        ZULIP_EMAIL: ${{ secrets.ZULIP_EMAIL }} 
        ZULIP_SITE: ${{ secrets.ZULIP_SITE }} 
        STREAM: ${{ secrets.STREAM }} 
      run: python run.py
      shell: sh
